/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EventsInner
 */
public class EventsInnerTest {
    private final EventsInner model = new EventsInner();

    /**
     * Model tests for EventsInner
     */
    @Test
    public void testEventsInner() {
        // TODO: test EventsInner
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'excerpt'
     */
    @Test
    public void excerptTest() {
        // TODO: test excerpt
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'theIdOfTheObjectAnswerCommaCommentCommaQuestionCommaOrUserTheEventDescribes'
     */
    @Test
    public void theIdOfTheObjectAnswerCommaCommentCommaQuestionCommaOrUserTheEventDescribesTest() {
        // TODO: test theIdOfTheObjectAnswerCommaCommentCommaQuestionCommaOrUserTheEventDescribes
    }

}
