/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InboxItemsInnerSiteStyling
 */
public class InboxItemsInnerSiteStylingTest {
    private final InboxItemsInnerSiteStyling model = new InboxItemsInnerSiteStyling();

    /**
     * Model tests for InboxItemsInnerSiteStyling
     */
    @Test
    public void testInboxItemsInnerSiteStyling() {
        // TODO: test InboxItemsInnerSiteStyling
    }

    /**
     * Test the property 'linkColor'
     */
    @Test
    public void linkColorTest() {
        // TODO: test linkColor
    }

    /**
     * Test the property 'tagBackgroundColor'
     */
    @Test
    public void tagBackgroundColorTest() {
        // TODO: test tagBackgroundColor
    }

    /**
     * Test the property 'tagForegroundColor'
     */
    @Test
    public void tagForegroundColorTest() {
        // TODO: test tagForegroundColor
    }

}
