/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReputationChangesInner
 */
public class ReputationChangesInnerTest {
    private final ReputationChangesInner model = new ReputationChangesInner();

    /**
     * Model tests for ReputationChangesInner
     */
    @Test
    public void testReputationChangesInner() {
        // TODO: test ReputationChangesInner
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'onDate'
     */
    @Test
    public void onDateTest() {
        // TODO: test onDate
    }

    /**
     * Test the property 'postId'
     */
    @Test
    public void postIdTest() {
        // TODO: test postId
    }

    /**
     * Test the property 'postType'
     */
    @Test
    public void postTypeTest() {
        // TODO: test postType
    }

    /**
     * Test the property 'reputationChange'
     */
    @Test
    public void reputationChangeTest() {
        // TODO: test reputationChange
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'voteType'
     */
    @Test
    public void voteTypeTest() {
        // TODO: test voteType
    }

}
