/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AnswersInnerLastEditor;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TagWikisInner
 */
public class TagWikisInnerTest {
    private final TagWikisInner model = new TagWikisInner();

    /**
     * Model tests for TagWikisInner
     */
    @Test
    public void testTagWikisInner() {
        // TODO: test TagWikisInner
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'bodyLastEditDate'
     */
    @Test
    public void bodyLastEditDateTest() {
        // TODO: test bodyLastEditDate
    }

    /**
     * Test the property 'excerpt'
     */
    @Test
    public void excerptTest() {
        // TODO: test excerpt
    }

    /**
     * Test the property 'excerptLastEditDate'
     */
    @Test
    public void excerptLastEditDateTest() {
        // TODO: test excerptLastEditDate
    }

    /**
     * Test the property 'lastBodyEditor'
     */
    @Test
    public void lastBodyEditorTest() {
        // TODO: test lastBodyEditor
    }

    /**
     * Test the property 'lastExcerptEditor'
     */
    @Test
    public void lastExcerptEditorTest() {
        // TODO: test lastExcerptEditor
    }

    /**
     * Test the property 'tagName'
     */
    @Test
    public void tagNameTest() {
        // TODO: test tagName
    }

}
