/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * AnswersInnerLastEditorBadgeCounts
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AnswersInnerLastEditorBadgeCounts {
  public static final String SERIALIZED_NAME_BRONZE = "bronze";
  @SerializedName(SERIALIZED_NAME_BRONZE)
  private Integer bronze;

  public static final String SERIALIZED_NAME_GOLD = "gold";
  @SerializedName(SERIALIZED_NAME_GOLD)
  private Integer gold;

  public static final String SERIALIZED_NAME_SILVER = "silver";
  @SerializedName(SERIALIZED_NAME_SILVER)
  private Integer silver;

  public AnswersInnerLastEditorBadgeCounts() {
  }

  public AnswersInnerLastEditorBadgeCounts bronze(Integer bronze) {
    
    
    
    
    this.bronze = bronze;
    return this;
  }

   /**
   * Get bronze
   * @return bronze
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getBronze() {
    return bronze;
  }


  public void setBronze(Integer bronze) {
    
    
    
    this.bronze = bronze;
  }


  public AnswersInnerLastEditorBadgeCounts gold(Integer gold) {
    
    
    
    
    this.gold = gold;
    return this;
  }

   /**
   * Get gold
   * @return gold
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getGold() {
    return gold;
  }


  public void setGold(Integer gold) {
    
    
    
    this.gold = gold;
  }


  public AnswersInnerLastEditorBadgeCounts silver(Integer silver) {
    
    
    
    
    this.silver = silver;
    return this;
  }

   /**
   * Get silver
   * @return silver
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSilver() {
    return silver;
  }


  public void setSilver(Integer silver) {
    
    
    
    this.silver = silver;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AnswersInnerLastEditorBadgeCounts instance itself
   */
  public AnswersInnerLastEditorBadgeCounts putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnswersInnerLastEditorBadgeCounts answersInnerLastEditorBadgeCounts = (AnswersInnerLastEditorBadgeCounts) o;
    return Objects.equals(this.bronze, answersInnerLastEditorBadgeCounts.bronze) &&
        Objects.equals(this.gold, answersInnerLastEditorBadgeCounts.gold) &&
        Objects.equals(this.silver, answersInnerLastEditorBadgeCounts.silver)&&
        Objects.equals(this.additionalProperties, answersInnerLastEditorBadgeCounts.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bronze, gold, silver, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnswersInnerLastEditorBadgeCounts {\n");
    sb.append("    bronze: ").append(toIndentedString(bronze)).append("\n");
    sb.append("    gold: ").append(toIndentedString(gold)).append("\n");
    sb.append("    silver: ").append(toIndentedString(silver)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bronze");
    openapiFields.add("gold");
    openapiFields.add("silver");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AnswersInnerLastEditorBadgeCounts
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AnswersInnerLastEditorBadgeCounts.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AnswersInnerLastEditorBadgeCounts is not found in the empty JSON string", AnswersInnerLastEditorBadgeCounts.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AnswersInnerLastEditorBadgeCounts.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AnswersInnerLastEditorBadgeCounts' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AnswersInnerLastEditorBadgeCounts> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AnswersInnerLastEditorBadgeCounts.class));

       return (TypeAdapter<T>) new TypeAdapter<AnswersInnerLastEditorBadgeCounts>() {
           @Override
           public void write(JsonWriter out, AnswersInnerLastEditorBadgeCounts value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AnswersInnerLastEditorBadgeCounts read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AnswersInnerLastEditorBadgeCounts instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AnswersInnerLastEditorBadgeCounts given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AnswersInnerLastEditorBadgeCounts
  * @throws IOException if the JSON string is invalid with respect to AnswersInnerLastEditorBadgeCounts
  */
  public static AnswersInnerLastEditorBadgeCounts fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AnswersInnerLastEditorBadgeCounts.class);
  }

 /**
  * Convert an instance of AnswersInnerLastEditorBadgeCounts to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

