/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * InboxItemsInnerSiteStyling
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InboxItemsInnerSiteStyling {
  public static final String SERIALIZED_NAME_LINK_COLOR = "link_color";
  @SerializedName(SERIALIZED_NAME_LINK_COLOR)
  private String linkColor;

  public static final String SERIALIZED_NAME_TAG_BACKGROUND_COLOR = "tag_background_color";
  @SerializedName(SERIALIZED_NAME_TAG_BACKGROUND_COLOR)
  private String tagBackgroundColor;

  public static final String SERIALIZED_NAME_TAG_FOREGROUND_COLOR = "tag_foreground_color";
  @SerializedName(SERIALIZED_NAME_TAG_FOREGROUND_COLOR)
  private String tagForegroundColor;

  public InboxItemsInnerSiteStyling() {
  }

  public InboxItemsInnerSiteStyling linkColor(String linkColor) {
    
    
    
    
    this.linkColor = linkColor;
    return this;
  }

   /**
   * Get linkColor
   * @return linkColor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLinkColor() {
    return linkColor;
  }


  public void setLinkColor(String linkColor) {
    
    
    
    this.linkColor = linkColor;
  }


  public InboxItemsInnerSiteStyling tagBackgroundColor(String tagBackgroundColor) {
    
    
    
    
    this.tagBackgroundColor = tagBackgroundColor;
    return this;
  }

   /**
   * Get tagBackgroundColor
   * @return tagBackgroundColor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTagBackgroundColor() {
    return tagBackgroundColor;
  }


  public void setTagBackgroundColor(String tagBackgroundColor) {
    
    
    
    this.tagBackgroundColor = tagBackgroundColor;
  }


  public InboxItemsInnerSiteStyling tagForegroundColor(String tagForegroundColor) {
    
    
    
    
    this.tagForegroundColor = tagForegroundColor;
    return this;
  }

   /**
   * Get tagForegroundColor
   * @return tagForegroundColor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTagForegroundColor() {
    return tagForegroundColor;
  }


  public void setTagForegroundColor(String tagForegroundColor) {
    
    
    
    this.tagForegroundColor = tagForegroundColor;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InboxItemsInnerSiteStyling instance itself
   */
  public InboxItemsInnerSiteStyling putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboxItemsInnerSiteStyling inboxItemsInnerSiteStyling = (InboxItemsInnerSiteStyling) o;
    return Objects.equals(this.linkColor, inboxItemsInnerSiteStyling.linkColor) &&
        Objects.equals(this.tagBackgroundColor, inboxItemsInnerSiteStyling.tagBackgroundColor) &&
        Objects.equals(this.tagForegroundColor, inboxItemsInnerSiteStyling.tagForegroundColor)&&
        Objects.equals(this.additionalProperties, inboxItemsInnerSiteStyling.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkColor, tagBackgroundColor, tagForegroundColor, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboxItemsInnerSiteStyling {\n");
    sb.append("    linkColor: ").append(toIndentedString(linkColor)).append("\n");
    sb.append("    tagBackgroundColor: ").append(toIndentedString(tagBackgroundColor)).append("\n");
    sb.append("    tagForegroundColor: ").append(toIndentedString(tagForegroundColor)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("link_color");
    openapiFields.add("tag_background_color");
    openapiFields.add("tag_foreground_color");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InboxItemsInnerSiteStyling
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InboxItemsInnerSiteStyling.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InboxItemsInnerSiteStyling is not found in the empty JSON string", InboxItemsInnerSiteStyling.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("link_color") != null && !jsonObj.get("link_color").isJsonNull()) && !jsonObj.get("link_color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `link_color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("link_color").toString()));
      }
      if ((jsonObj.get("tag_background_color") != null && !jsonObj.get("tag_background_color").isJsonNull()) && !jsonObj.get("tag_background_color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tag_background_color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tag_background_color").toString()));
      }
      if ((jsonObj.get("tag_foreground_color") != null && !jsonObj.get("tag_foreground_color").isJsonNull()) && !jsonObj.get("tag_foreground_color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tag_foreground_color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tag_foreground_color").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InboxItemsInnerSiteStyling.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InboxItemsInnerSiteStyling' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InboxItemsInnerSiteStyling> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InboxItemsInnerSiteStyling.class));

       return (TypeAdapter<T>) new TypeAdapter<InboxItemsInnerSiteStyling>() {
           @Override
           public void write(JsonWriter out, InboxItemsInnerSiteStyling value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InboxItemsInnerSiteStyling read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InboxItemsInnerSiteStyling instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InboxItemsInnerSiteStyling given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InboxItemsInnerSiteStyling
  * @throws IOException if the JSON string is invalid with respect to InboxItemsInnerSiteStyling
  */
  public static InboxItemsInnerSiteStyling fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InboxItemsInnerSiteStyling.class);
  }

 /**
  * Convert an instance of InboxItemsInnerSiteStyling to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

