/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InboxItemsInnerSite;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * InfoObject
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InfoObject {
  public static final String SERIALIZED_NAME_ANSWERS_PER_MINUTE = "answers_per_minute";
  @SerializedName(SERIALIZED_NAME_ANSWERS_PER_MINUTE)
  private Double answersPerMinute;

  public static final String SERIALIZED_NAME_API_REVISION = "api_revision";
  @SerializedName(SERIALIZED_NAME_API_REVISION)
  private String apiRevision;

  public static final String SERIALIZED_NAME_BADGES_PER_MINUTE = "badges_per_minute";
  @SerializedName(SERIALIZED_NAME_BADGES_PER_MINUTE)
  private Double badgesPerMinute;

  public static final String SERIALIZED_NAME_NEW_ACTIVE_USERS = "new_active_users";
  @SerializedName(SERIALIZED_NAME_NEW_ACTIVE_USERS)
  private Integer newActiveUsers;

  public static final String SERIALIZED_NAME_QUESTIONS_PER_MINUTE = "questions_per_minute";
  @SerializedName(SERIALIZED_NAME_QUESTIONS_PER_MINUTE)
  private Double questionsPerMinute;

  public static final String SERIALIZED_NAME_SITE = "site";
  @SerializedName(SERIALIZED_NAME_SITE)
  private InboxItemsInnerSite site;

  public static final String SERIALIZED_NAME_TOTAL_ACCEPTED = "total_accepted";
  @SerializedName(SERIALIZED_NAME_TOTAL_ACCEPTED)
  private Integer totalAccepted;

  public static final String SERIALIZED_NAME_TOTAL_ANSWERS = "total_answers";
  @SerializedName(SERIALIZED_NAME_TOTAL_ANSWERS)
  private Integer totalAnswers;

  public static final String SERIALIZED_NAME_TOTAL_BADGES = "total_badges";
  @SerializedName(SERIALIZED_NAME_TOTAL_BADGES)
  private Integer totalBadges;

  public static final String SERIALIZED_NAME_TOTAL_COMMENTS = "total_comments";
  @SerializedName(SERIALIZED_NAME_TOTAL_COMMENTS)
  private Integer totalComments;

  public static final String SERIALIZED_NAME_TOTAL_QUESTIONS = "total_questions";
  @SerializedName(SERIALIZED_NAME_TOTAL_QUESTIONS)
  private Integer totalQuestions;

  public static final String SERIALIZED_NAME_TOTAL_UNANSWERED = "total_unanswered";
  @SerializedName(SERIALIZED_NAME_TOTAL_UNANSWERED)
  private Integer totalUnanswered;

  public static final String SERIALIZED_NAME_TOTAL_USERS = "total_users";
  @SerializedName(SERIALIZED_NAME_TOTAL_USERS)
  private Integer totalUsers;

  public static final String SERIALIZED_NAME_TOTAL_VOTES = "total_votes";
  @SerializedName(SERIALIZED_NAME_TOTAL_VOTES)
  private Integer totalVotes;

  public InfoObject() {
  }

  public InfoObject answersPerMinute(Double answersPerMinute) {
    
    
    
    
    this.answersPerMinute = answersPerMinute;
    return this;
  }

  public InfoObject answersPerMinute(Integer answersPerMinute) {
    
    
    
    
    this.answersPerMinute = answersPerMinute.doubleValue();
    return this;
  }

   /**
   * Get answersPerMinute
   * @return answersPerMinute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getAnswersPerMinute() {
    return answersPerMinute;
  }


  public void setAnswersPerMinute(Double answersPerMinute) {
    
    
    
    this.answersPerMinute = answersPerMinute;
  }


  public InfoObject apiRevision(String apiRevision) {
    
    
    
    
    this.apiRevision = apiRevision;
    return this;
  }

   /**
   * Get apiRevision
   * @return apiRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getApiRevision() {
    return apiRevision;
  }


  public void setApiRevision(String apiRevision) {
    
    
    
    this.apiRevision = apiRevision;
  }


  public InfoObject badgesPerMinute(Double badgesPerMinute) {
    
    
    
    
    this.badgesPerMinute = badgesPerMinute;
    return this;
  }

  public InfoObject badgesPerMinute(Integer badgesPerMinute) {
    
    
    
    
    this.badgesPerMinute = badgesPerMinute.doubleValue();
    return this;
  }

   /**
   * Get badgesPerMinute
   * @return badgesPerMinute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getBadgesPerMinute() {
    return badgesPerMinute;
  }


  public void setBadgesPerMinute(Double badgesPerMinute) {
    
    
    
    this.badgesPerMinute = badgesPerMinute;
  }


  public InfoObject newActiveUsers(Integer newActiveUsers) {
    
    
    
    
    this.newActiveUsers = newActiveUsers;
    return this;
  }

   /**
   * Get newActiveUsers
   * @return newActiveUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNewActiveUsers() {
    return newActiveUsers;
  }


  public void setNewActiveUsers(Integer newActiveUsers) {
    
    
    
    this.newActiveUsers = newActiveUsers;
  }


  public InfoObject questionsPerMinute(Double questionsPerMinute) {
    
    
    
    
    this.questionsPerMinute = questionsPerMinute;
    return this;
  }

  public InfoObject questionsPerMinute(Integer questionsPerMinute) {
    
    
    
    
    this.questionsPerMinute = questionsPerMinute.doubleValue();
    return this;
  }

   /**
   * Get questionsPerMinute
   * @return questionsPerMinute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getQuestionsPerMinute() {
    return questionsPerMinute;
  }


  public void setQuestionsPerMinute(Double questionsPerMinute) {
    
    
    
    this.questionsPerMinute = questionsPerMinute;
  }


  public InfoObject site(InboxItemsInnerSite site) {
    
    
    
    
    this.site = site;
    return this;
  }

   /**
   * Get site
   * @return site
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InboxItemsInnerSite getSite() {
    return site;
  }


  public void setSite(InboxItemsInnerSite site) {
    
    
    
    this.site = site;
  }


  public InfoObject totalAccepted(Integer totalAccepted) {
    
    
    
    
    this.totalAccepted = totalAccepted;
    return this;
  }

   /**
   * Get totalAccepted
   * @return totalAccepted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalAccepted() {
    return totalAccepted;
  }


  public void setTotalAccepted(Integer totalAccepted) {
    
    
    
    this.totalAccepted = totalAccepted;
  }


  public InfoObject totalAnswers(Integer totalAnswers) {
    
    
    
    
    this.totalAnswers = totalAnswers;
    return this;
  }

   /**
   * Get totalAnswers
   * @return totalAnswers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalAnswers() {
    return totalAnswers;
  }


  public void setTotalAnswers(Integer totalAnswers) {
    
    
    
    this.totalAnswers = totalAnswers;
  }


  public InfoObject totalBadges(Integer totalBadges) {
    
    
    
    
    this.totalBadges = totalBadges;
    return this;
  }

   /**
   * Get totalBadges
   * @return totalBadges
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalBadges() {
    return totalBadges;
  }


  public void setTotalBadges(Integer totalBadges) {
    
    
    
    this.totalBadges = totalBadges;
  }


  public InfoObject totalComments(Integer totalComments) {
    
    
    
    
    this.totalComments = totalComments;
    return this;
  }

   /**
   * Get totalComments
   * @return totalComments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalComments() {
    return totalComments;
  }


  public void setTotalComments(Integer totalComments) {
    
    
    
    this.totalComments = totalComments;
  }


  public InfoObject totalQuestions(Integer totalQuestions) {
    
    
    
    
    this.totalQuestions = totalQuestions;
    return this;
  }

   /**
   * Get totalQuestions
   * @return totalQuestions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalQuestions() {
    return totalQuestions;
  }


  public void setTotalQuestions(Integer totalQuestions) {
    
    
    
    this.totalQuestions = totalQuestions;
  }


  public InfoObject totalUnanswered(Integer totalUnanswered) {
    
    
    
    
    this.totalUnanswered = totalUnanswered;
    return this;
  }

   /**
   * Get totalUnanswered
   * @return totalUnanswered
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalUnanswered() {
    return totalUnanswered;
  }


  public void setTotalUnanswered(Integer totalUnanswered) {
    
    
    
    this.totalUnanswered = totalUnanswered;
  }


  public InfoObject totalUsers(Integer totalUsers) {
    
    
    
    
    this.totalUsers = totalUsers;
    return this;
  }

   /**
   * Get totalUsers
   * @return totalUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalUsers() {
    return totalUsers;
  }


  public void setTotalUsers(Integer totalUsers) {
    
    
    
    this.totalUsers = totalUsers;
  }


  public InfoObject totalVotes(Integer totalVotes) {
    
    
    
    
    this.totalVotes = totalVotes;
    return this;
  }

   /**
   * Get totalVotes
   * @return totalVotes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalVotes() {
    return totalVotes;
  }


  public void setTotalVotes(Integer totalVotes) {
    
    
    
    this.totalVotes = totalVotes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InfoObject instance itself
   */
  public InfoObject putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoObject infoObject = (InfoObject) o;
    return Objects.equals(this.answersPerMinute, infoObject.answersPerMinute) &&
        Objects.equals(this.apiRevision, infoObject.apiRevision) &&
        Objects.equals(this.badgesPerMinute, infoObject.badgesPerMinute) &&
        Objects.equals(this.newActiveUsers, infoObject.newActiveUsers) &&
        Objects.equals(this.questionsPerMinute, infoObject.questionsPerMinute) &&
        Objects.equals(this.site, infoObject.site) &&
        Objects.equals(this.totalAccepted, infoObject.totalAccepted) &&
        Objects.equals(this.totalAnswers, infoObject.totalAnswers) &&
        Objects.equals(this.totalBadges, infoObject.totalBadges) &&
        Objects.equals(this.totalComments, infoObject.totalComments) &&
        Objects.equals(this.totalQuestions, infoObject.totalQuestions) &&
        Objects.equals(this.totalUnanswered, infoObject.totalUnanswered) &&
        Objects.equals(this.totalUsers, infoObject.totalUsers) &&
        Objects.equals(this.totalVotes, infoObject.totalVotes)&&
        Objects.equals(this.additionalProperties, infoObject.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(answersPerMinute, apiRevision, badgesPerMinute, newActiveUsers, questionsPerMinute, site, totalAccepted, totalAnswers, totalBadges, totalComments, totalQuestions, totalUnanswered, totalUsers, totalVotes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoObject {\n");
    sb.append("    answersPerMinute: ").append(toIndentedString(answersPerMinute)).append("\n");
    sb.append("    apiRevision: ").append(toIndentedString(apiRevision)).append("\n");
    sb.append("    badgesPerMinute: ").append(toIndentedString(badgesPerMinute)).append("\n");
    sb.append("    newActiveUsers: ").append(toIndentedString(newActiveUsers)).append("\n");
    sb.append("    questionsPerMinute: ").append(toIndentedString(questionsPerMinute)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("    totalAccepted: ").append(toIndentedString(totalAccepted)).append("\n");
    sb.append("    totalAnswers: ").append(toIndentedString(totalAnswers)).append("\n");
    sb.append("    totalBadges: ").append(toIndentedString(totalBadges)).append("\n");
    sb.append("    totalComments: ").append(toIndentedString(totalComments)).append("\n");
    sb.append("    totalQuestions: ").append(toIndentedString(totalQuestions)).append("\n");
    sb.append("    totalUnanswered: ").append(toIndentedString(totalUnanswered)).append("\n");
    sb.append("    totalUsers: ").append(toIndentedString(totalUsers)).append("\n");
    sb.append("    totalVotes: ").append(toIndentedString(totalVotes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("answers_per_minute");
    openapiFields.add("api_revision");
    openapiFields.add("badges_per_minute");
    openapiFields.add("new_active_users");
    openapiFields.add("questions_per_minute");
    openapiFields.add("site");
    openapiFields.add("total_accepted");
    openapiFields.add("total_answers");
    openapiFields.add("total_badges");
    openapiFields.add("total_comments");
    openapiFields.add("total_questions");
    openapiFields.add("total_unanswered");
    openapiFields.add("total_users");
    openapiFields.add("total_votes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InfoObject
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InfoObject.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InfoObject is not found in the empty JSON string", InfoObject.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("api_revision") != null && !jsonObj.get("api_revision").isJsonNull()) && !jsonObj.get("api_revision").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `api_revision` to be a primitive type in the JSON string but got `%s`", jsonObj.get("api_revision").toString()));
      }
      // validate the optional field `site`
      if (jsonObj.get("site") != null && !jsonObj.get("site").isJsonNull()) {
        InboxItemsInnerSite.validateJsonObject(jsonObj.getAsJsonObject("site"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InfoObject.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InfoObject' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InfoObject> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InfoObject.class));

       return (TypeAdapter<T>) new TypeAdapter<InfoObject>() {
           @Override
           public void write(JsonWriter out, InfoObject value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InfoObject read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InfoObject instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InfoObject given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InfoObject
  * @throws IOException if the JSON string is invalid with respect to InfoObject
  */
  public static InfoObject fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InfoObject.class);
  }

 /**
  * Convert an instance of InfoObject to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

