/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * QuestionsInnerClosedDetails
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class QuestionsInnerClosedDetails {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_BY_USERS = "by_users";
  @SerializedName(SERIALIZED_NAME_BY_USERS)
  private List<Object> byUsers = null;

  public static final String SERIALIZED_NAME_ON_HOLD = "on_hold";
  @SerializedName(SERIALIZED_NAME_ON_HOLD)
  private Boolean onHold;

  public static final String SERIALIZED_NAME_ORIGINAL_QUESTIONS = "original_questions";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_QUESTIONS)
  private List<Object> originalQuestions = null;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public QuestionsInnerClosedDetails() {
  }

  public QuestionsInnerClosedDetails description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public QuestionsInnerClosedDetails byUsers(List<Object> byUsers) {
    
    
    
    
    this.byUsers = byUsers;
    return this;
  }

  public QuestionsInnerClosedDetails addByUsersItem(Object byUsersItem) {
    if (this.byUsers == null) {
      this.byUsers = new ArrayList<>();
    }
    this.byUsers.add(byUsersItem);
    return this;
  }

   /**
   * Get byUsers
   * @return byUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getByUsers() {
    return byUsers;
  }


  public void setByUsers(List<Object> byUsers) {
    
    
    
    this.byUsers = byUsers;
  }


  public QuestionsInnerClosedDetails onHold(Boolean onHold) {
    
    
    
    
    this.onHold = onHold;
    return this;
  }

   /**
   * Get onHold
   * @return onHold
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOnHold() {
    return onHold;
  }


  public void setOnHold(Boolean onHold) {
    
    
    
    this.onHold = onHold;
  }


  public QuestionsInnerClosedDetails originalQuestions(List<Object> originalQuestions) {
    
    
    
    
    this.originalQuestions = originalQuestions;
    return this;
  }

  public QuestionsInnerClosedDetails addOriginalQuestionsItem(Object originalQuestionsItem) {
    if (this.originalQuestions == null) {
      this.originalQuestions = new ArrayList<>();
    }
    this.originalQuestions.add(originalQuestionsItem);
    return this;
  }

   /**
   * Get originalQuestions
   * @return originalQuestions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getOriginalQuestions() {
    return originalQuestions;
  }


  public void setOriginalQuestions(List<Object> originalQuestions) {
    
    
    
    this.originalQuestions = originalQuestions;
  }


  public QuestionsInnerClosedDetails reason(String reason) {
    
    
    
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    
    
    
    this.reason = reason;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the QuestionsInnerClosedDetails instance itself
   */
  public QuestionsInnerClosedDetails putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuestionsInnerClosedDetails questionsInnerClosedDetails = (QuestionsInnerClosedDetails) o;
    return Objects.equals(this.description, questionsInnerClosedDetails.description) &&
        Objects.equals(this.byUsers, questionsInnerClosedDetails.byUsers) &&
        Objects.equals(this.onHold, questionsInnerClosedDetails.onHold) &&
        Objects.equals(this.originalQuestions, questionsInnerClosedDetails.originalQuestions) &&
        Objects.equals(this.reason, questionsInnerClosedDetails.reason)&&
        Objects.equals(this.additionalProperties, questionsInnerClosedDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, byUsers, onHold, originalQuestions, reason, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuestionsInnerClosedDetails {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    byUsers: ").append(toIndentedString(byUsers)).append("\n");
    sb.append("    onHold: ").append(toIndentedString(onHold)).append("\n");
    sb.append("    originalQuestions: ").append(toIndentedString(originalQuestions)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("by_users");
    openapiFields.add("on_hold");
    openapiFields.add("original_questions");
    openapiFields.add("reason");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to QuestionsInnerClosedDetails
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!QuestionsInnerClosedDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QuestionsInnerClosedDetails is not found in the empty JSON string", QuestionsInnerClosedDetails.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("by_users") != null && !jsonObj.get("by_users").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `by_users` to be an array in the JSON string but got `%s`", jsonObj.get("by_users").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("original_questions") != null && !jsonObj.get("original_questions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `original_questions` to be an array in the JSON string but got `%s`", jsonObj.get("original_questions").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QuestionsInnerClosedDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QuestionsInnerClosedDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QuestionsInnerClosedDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QuestionsInnerClosedDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<QuestionsInnerClosedDetails>() {
           @Override
           public void write(JsonWriter out, QuestionsInnerClosedDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public QuestionsInnerClosedDetails read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             QuestionsInnerClosedDetails instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of QuestionsInnerClosedDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of QuestionsInnerClosedDetails
  * @throws IOException if the JSON string is invalid with respect to QuestionsInnerClosedDetails
  */
  public static QuestionsInnerClosedDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QuestionsInnerClosedDetails.class);
  }

 /**
  * Convert an instance of QuestionsInnerClosedDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

