/*
 * StackExchange
 * Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ReputationHistoryInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ReputationHistoryInner {
  public static final String SERIALIZED_NAME_CREATION_DATE = "creation_date";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  private Integer creationDate;

  public static final String SERIALIZED_NAME_POST_ID = "post_id";
  @SerializedName(SERIALIZED_NAME_POST_ID)
  private Integer postId;

  public static final String SERIALIZED_NAME_REPUTATION_CHANGE = "reputation_change";
  @SerializedName(SERIALIZED_NAME_REPUTATION_CHANGE)
  private Integer reputationChange;

  public static final String SERIALIZED_NAME_REPUTATION_HISTORY_TYPE = "reputation_history_type";
  @SerializedName(SERIALIZED_NAME_REPUTATION_HISTORY_TYPE)
  private String reputationHistoryType;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public ReputationHistoryInner() {
  }

  public ReputationHistoryInner creationDate(Integer creationDate) {
    
    
    
    
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCreationDate() {
    return creationDate;
  }


  public void setCreationDate(Integer creationDate) {
    
    
    
    this.creationDate = creationDate;
  }


  public ReputationHistoryInner postId(Integer postId) {
    
    
    
    
    this.postId = postId;
    return this;
  }

   /**
   * Get postId
   * @return postId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPostId() {
    return postId;
  }


  public void setPostId(Integer postId) {
    
    
    
    this.postId = postId;
  }


  public ReputationHistoryInner reputationChange(Integer reputationChange) {
    
    
    
    
    this.reputationChange = reputationChange;
    return this;
  }

   /**
   * Get reputationChange
   * @return reputationChange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReputationChange() {
    return reputationChange;
  }


  public void setReputationChange(Integer reputationChange) {
    
    
    
    this.reputationChange = reputationChange;
  }


  public ReputationHistoryInner reputationHistoryType(String reputationHistoryType) {
    
    
    
    
    this.reputationHistoryType = reputationHistoryType;
    return this;
  }

   /**
   * Get reputationHistoryType
   * @return reputationHistoryType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReputationHistoryType() {
    return reputationHistoryType;
  }


  public void setReputationHistoryType(String reputationHistoryType) {
    
    
    
    this.reputationHistoryType = reputationHistoryType;
  }


  public ReputationHistoryInner userId(Integer userId) {
    
    
    
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getUserId() {
    return userId;
  }


  public void setUserId(Integer userId) {
    
    
    
    this.userId = userId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReputationHistoryInner instance itself
   */
  public ReputationHistoryInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReputationHistoryInner reputationHistoryInner = (ReputationHistoryInner) o;
    return Objects.equals(this.creationDate, reputationHistoryInner.creationDate) &&
        Objects.equals(this.postId, reputationHistoryInner.postId) &&
        Objects.equals(this.reputationChange, reputationHistoryInner.reputationChange) &&
        Objects.equals(this.reputationHistoryType, reputationHistoryInner.reputationHistoryType) &&
        Objects.equals(this.userId, reputationHistoryInner.userId)&&
        Objects.equals(this.additionalProperties, reputationHistoryInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, postId, reputationChange, reputationHistoryType, userId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReputationHistoryInner {\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    postId: ").append(toIndentedString(postId)).append("\n");
    sb.append("    reputationChange: ").append(toIndentedString(reputationChange)).append("\n");
    sb.append("    reputationHistoryType: ").append(toIndentedString(reputationHistoryType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("creation_date");
    openapiFields.add("post_id");
    openapiFields.add("reputation_change");
    openapiFields.add("reputation_history_type");
    openapiFields.add("user_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReputationHistoryInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReputationHistoryInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReputationHistoryInner is not found in the empty JSON string", ReputationHistoryInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("reputation_history_type") != null && !jsonObj.get("reputation_history_type").isJsonNull()) && !jsonObj.get("reputation_history_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reputation_history_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reputation_history_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReputationHistoryInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReputationHistoryInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReputationHistoryInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReputationHistoryInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ReputationHistoryInner>() {
           @Override
           public void write(JsonWriter out, ReputationHistoryInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReputationHistoryInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ReputationHistoryInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReputationHistoryInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReputationHistoryInner
  * @throws IOException if the JSON string is invalid with respect to ReputationHistoryInner
  */
  public static ReputationHistoryInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReputationHistoryInner.class);
  }

 /**
  * Convert an instance of ReputationHistoryInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

